apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: transmssion
          image: prom/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - mountPath: /etc/prometheus/prometheus.yml
              name: config
      volumes:
        - name: config
          hostPath:
            path: /home/tbo/bitmovin-iw/kube/config/prometheus.yml
            type: File
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  ports:
    - port: 9090
      protocol: TCP
  selector:
    app: prometheus
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: {}
  name: prometheus-ingress
spec:
  rules:
    - host: prometheus.home.int.itprof.sk
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090
    - host: prometheus.home.ext.itprof.sk
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090
